config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :username, presence:true
  validates :body, presence:true, length: {maximum: 200}
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence:true,
                        length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  validates :email, presence:true,
                        length: {minimum: 10}
  validates :encrypted_password, presence:true,
                        length: {minimum:5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

  before_action :set_default_locale

  private def set_default_locale
    I18n.default_locale= :hu
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    I18n.locale = :hu
    before_action :require_login
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end

    private def comment_params
        params.require(:comment).permit(:username, :body)
    end
end
 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :require_login
    def about
        @title = 'About Us';
        @content = 'This is the about pages';
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_login
    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end
    
    def new
        @post = Post.new
    end

    def create
        #render plain: params[:post].inspect
        @post = Post.new(post_params)

        if(@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to posts_path
    end
    private def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3><%= t('comment')%></h3>
<% @post.comments.each do |comment| %>
    <div class="well">
        <p><strong><%= comment.username %></strong>: <%= comment.body %>
            <%= link_to '[X]', [comment.post,comment], method: :delete, data: {confirm: t('confirm') }%>
        </p>
    </div>
<% end %>

app/views/comments/_form.html.erb
<h3><%= t('addcomment')%></h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label t('username') %><br>
        <%= f.text_field(:username, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label t('body') %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit(t('comments'), {:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fociblog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>

    <section>
     <div id="flash">
        <% flash.each do |key, value| %>
         <div class="flash <%= key %>"><%= value %></div>
       <% end %>
    </div>     
   </section>

  <nav class="navbar navbar-default-bg:blue">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Foci blog</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Főoldal", home_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if signed_in? %>
              <div class="well">
              Bejelentkezve: <%= current_user.email %> <%= button_to 'Kijelentkezés', sign_out_path, method: :delete, class: 'btn btn-primary' %>
              </div>
            <% else %>
              <%= link_to 'Bejelentkezés', sign_in_path %>
            <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Új poszt", new_post_path %></li>
        </ul>
        
      </div>
    </div>
  </nav>
  <div class="container">
  <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1><%= t('postupdate')%></h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label t('title') %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label t('body') %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.submit(t('update'),{:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/index.html.erb
<h1><%= t('posts')%></h1>
<% @posts.each do |post| %>
    <div class="well">
        <h3><%= post.title %></h3>
        <p><%= post.body %></p>
        <%= link_to t('read'), post_path(post), :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1><%= t('newpost')%></h1>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label t('title')%><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label t('body') %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.submit(t('add'), {:class => 'btn btn-primary'})%>
    </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to t('update'), edit_post_path(@post), :class => 'btn btn-primary' %>
<%= link_to t('delete'), post_path(@post),method: :delete, data: {confirm: t('confirm')}, :class => 'btn btn-danger' %>
<hr>
<%= render 'comments/comments' %>
<%= render 'comments/form' %>

app/views/users/_form.html.erb
<div class="text-field well">
  <%= form.label :Email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field well">
  <%= form.label :Jelszó %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit({:class => 'btn btn-primary'}) %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>